apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: myapp
      labels:
        tier: front-end
    spec:
      containers:
        - name: myapp
          image: nginx
