apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: myapp
      labels:
        tier: front-end
    spec:
      containers:
        - name: myapp
          image: nginx
