apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    tier: front-end
spec: 
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: 1
        memory: 255Mi
      limits:
        cpu: 2
        memory: 512Mi