apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      name: myapp
      labels:
        tier: front-end
    spec:
      containers:
        - name: myapp
          image: nginx
