apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    tier: front-end
spec: 
  containers:
  - name: nginx-container
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: size
                operator: In
                values:
                  - large 
          weight: 1